// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import { SideNav } from "./side-nav";

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="containers bg-gradient-to-t from-gray-950 to-black  mx-auto min-h-screen ">
      <div className=" flex  ">
        <SideNav />
        <div className="w-full px-11">{children}</div>
      </div>
    </main>
  );
}
