import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import ConvexClientProvider from "./ConvexClientProvider";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@components/layout/Navbar";
import BottomBar2 from "@components/layout/BottomBar2";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          <main className="relative">
            <Navbar />
            <section className="flex ">
              <Toaster />
              {children}
            </section>
          </main>
          <BottomBar2/>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
